# Generated by Django 2.1.2 on 2019-01-20 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_site_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
